name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      
      - name: Get pydo
        working-directory: ${{ github.workspace }}
        run: |
          git clone git://github.com/ali1234/pydo
          cd pydo && pip3 install .
      
      - name: apt install deps
        run: sudo apt install libc6:i386 libstdc++6:i386 libgcc1:i386 \
                 libncurses5:i386 libtinfo5:i386 zlib1g:i386 \
                 build-essential git bc python zip wget gettext \
                 autoconf automake libtool pkg-config autopoint \
                 bison flex libglib2.0-dev gobject-introspection \
                 multistrap fakeroot fakechroot proot cpio \
                 qemu-user binfmt-support makedev \
                 gtk-doc-tools valac libssl-dev

      - name: Build sd card
        working-directory: ${{ github.workspace }}
        run: |
          git clone https://github.com/gadgetoid/rpi-ramdisk -b keybow
          cd rpi-ramdisk
          git checkout keybow
          git submodule update --init --depth=1 kernel/linux
          git submodule update --init --depth=1 firmware/usbboot
          cp configs/keybow.config.py config.py
          pydo --init
          pydo :build -s10
