name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Build sd card
        working-directory: ${{ github.workspace }}
        run: |
          git clone https://github.com/gadgetoid/rpi-ramdisk -b keybow
          cd rpi-ramdisk
          git checkout keybow
          git submodule update --init --depth=1 kernel/linux
          git submodule update --init --depth=1 firmware/usbboot
          cp configs/keybow.config.py config.py
          ./build-docker
